# Generated by Django 5.2.8 on 2025-11-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_client_owner_mailing_owner_message_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': (('can_view_all_clients', 'Может просматривать всех клиентов'),), 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': (('can_view_all_mailings', 'Может просматривать все рассылки'), ('can_disable_mailings', 'Может отключать рассылки')), 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': (('can_view_all_messages', 'Может просматривать все сообщения'),), 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
